version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
                   
            - /home/lavanya/sql:/var/lib/mysql
        networks:
            - default
    php-httpd:
        image: php:7.2-apache
        ports: 
            - "80:80"
        volumes:
            - /home/lavanya/php:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        